/*  =========================================================================
    alert-list - ALERT-LIST wrapper

    Copyright (c) the Authors

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef alert_list_library_H_INCLUDED
#define alert_list_library_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <malamute.h>
#include <biosproto.h>

//  ALERT-LIST version macros for compile-time API detection

#define ALERT_LIST_VERSION_MAJOR 0
#define ALERT_LIST_VERSION_MINOR 1
#define ALERT_LIST_VERSION_PATCH 0

#define ALERT_LIST_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ALERT_LIST_VERSION \
    ALERT_LIST_MAKE_VERSION(ALERT_LIST_VERSION_MAJOR, ALERT_LIST_VERSION_MINOR, ALERT_LIST_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBALERT_LIST_STATIC
#       define ALERT_LIST_EXPORT
#   elif defined LIBALERT_LIST_EXPORTS
#       define ALERT_LIST_EXPORT __declspec(dllexport)
#   else
#       define ALERT_LIST_EXPORT __declspec(dllimport)
#   endif
#else
#   define ALERT_LIST_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _bios_alerts_list_server_t bios_alerts_list_server_t;
#define BIOS_ALERTS_LIST_SERVER_T_DEFINED


//  Public API classes
#include "bios_alerts_list_server.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
