/*  =========================================================================
    fty_alert_list_classes - private header file

    Copyright (C) 2014 - 2017 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_ALERT_LIST_CLASSES_H_INCLUDED
#define FTY_ALERT_LIST_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/fty_alert_list.h"

//  Extra headers

//  Opaque class structures to allow forward references
#ifndef ALERTS_UTILS_T_DEFINED
typedef struct _alerts_utils_t alerts_utils_t;
#define ALERTS_UTILS_T_DEFINED
#endif
#ifndef BIOS_PROTO_T_DEFINED
typedef struct _bios_proto_t bios_proto_t;
#define BIOS_PROTO_T_DEFINED
#endif

//  Internal API

#include "alerts_utils.h"
#include "bios_proto.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef FTY_ALERT_LIST_BUILD_DRAFT_API

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_ALERT_LIST_PRIVATE void
    alerts_utils_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_ALERT_LIST_PRIVATE void
    bios_proto_test (bool verbose);

//  Self test for private classes
FTY_ALERT_LIST_PRIVATE void
    fty_alert_list_private_selftest (bool verbose);

#endif // FTY_ALERT_LIST_BUILD_DRAFT_API

#endif
